services:
  - type: web
    name: db-pulse
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: APP_USERNAME
        value: admin
      - key: APP_PASSWORD
        sync: false
      - key: METADATA_DATABASE_URL
        sync: false
      - key: HEALTH_API_KEY
        sync: false
